[package]
name = "espadeiro_pt"
version = "6.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
comrak = "0.29.0"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
rss = "2.0.7"
serde = { version = "1.0.215", features = ["derive"] }
tera = "1.20.0"
toml = "0.8.19"
